#!/bin/bash


# Standard actuator turbine models.
wmake src/turbineModels/turbineModelsStandard

#wmake src/meshTools

# Custom function objects (this includes planar and temporal averaging, and lidar sampling).
#wmake src/functionObjects/field
#wmake src/functionObjects/utilities


# The atmospheric LES solver for precursors.
wmake applications/solvers/pimpleALMFoam
