#!/bin/bash


# Standard actuator turbine models.
wclean src/turbineModels/turbineModelsStandard

# Custom mesh Tools
#wclean src/meshTools


# Custom function objects (this includes planar and temporal averaging, and lidar sampling).
#wclean src/functionObjects/field
#wclean src/functionObjects/utilities


# The atmospheric LES solver for precursors.
wclean applications/solvers/pimpleALMFoam

