#!/bin/bash
OpenFOAM-8-gcc-central()
{
   # Important locations.
   export inst_loc=/opt/openfoam8
   export sowfa_loc=/home/$USER/OpenFOAM

   # Set the OpenFOAM version and installation directory
   export OPENFOAM_VERSION=8
   export OPENFOAM_NAME=openfoam$OPENFOAM_VERSION
   export FOAM_INST_DIR=$inst_loc
   export WM_PROJECT_USER_DIR=/home/$USER/$USER-$OPENFOAM_VERSION
   export FOAMY_HEX_MESH=false

   # Set the SOWFA installation directory.
   export SOWFA_DIR=$sowfa_loc/SOWFA-8
   export SOWFA_APPBIN=$SOWFA_DIR/platforms/$WM_OPTIONS/bin
   export SOWFA_LIBBIN=$SOWFA_DIR/platforms/$WM_OPTIONS/lib
}
